name: Deploy Backend to Beanstalk (monorepo)
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'          # only run when backend changes
      - '.github/workflows/deploy-beanstalk.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'   # or 17

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('backend/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Build
        run: mvn -B -DskipTests package

      - name: Prepare EB bundle
        run: |
          set -euo pipefail
          rm -rf bundle && mkdir -p bundle/.ebextensions

          # pick the boot 'repackaged' jar deterministically
          JAR=$(ls target/*-SNAPSHOT.jar 2>/dev/null || ls target/*.jar | head -n 1)
          echo "Using JAR: $JAR"
          cp "$JAR" bundle/app.jar

          # --- Procfile: bind to the EB-provided port (usually 5000) ---
          # This ensures Tomcat listens where Nginx expects it.
          cat > bundle/Procfile <<'EOF'
          web: bash -lc 'java -Dserver.port=${PORT:-5000} -jar app.jar'
          EOF

          # normalize line endings just in case
          sed -i 's/\r$//' bundle/Procfile

          # include EB health config if present
          [ -f .ebextensions/00-health.config ] && cp .ebextensions/00-health.config bundle/.ebextensions/00-health.config

          # runtime properties so Spring binds to PORT (default 5000 if not set)
          cat > bundle/application.properties <<'PROPS'
          server.port=${PORT:5000}
          PROPS
          
          # Fail if jar is not executable (no Main-Class)
          if ! unzip -p bundle/app.jar META-INF/MANIFEST.MF | grep -qi '^Main-Class:'; then
            echo "ERROR: app.jar is not executable (no Main-Class in MANIFEST)."
            unzip -p bundle/app.jar META-INF/MANIFEST.MF || true
            exit 1
          fi

          # zip *contents* of bundle (so files are at the root of the zip)
          cd bundle && zip -r ../deploy.zip .

      - name: Verify deploy.zip contents
        run: |
          set -euo pipefail
          echo "---- Listing deploy.zip ----"
          unzip -l deploy.zip | sed -n '1,200p'
          
          echo "---- Sanity checks ----"
          # must be at the root (no leading bundle/)
          unzip -l deploy.zip | awk '{print $4}' | grep -qx "Procfile" || { echo "ERROR: Procfile not at zip root"; exit 1; }
          unzip -l deploy.zip | awk '{print $4}' | grep -qx "app.jar"   || { echo "ERROR: app.jar not at zip root"; exit 1; }
          
          echo "---- Procfile content ----"
          unzip -p deploy.zip Procfile || { echo "ERROR: Cannot read Procfile from zip"; exit 1; }
          echo "---- application.properties ----"
          unzip -p deploy.zip application.properties || { echo "ERROR: Cannot read application.properties"; exit 1; }

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: memorials-api
          environment_name: memorials-api-env
          region: eu-west-2
          version_label: v-${{ github.run_number }}
          deployment_package: backend/deploy.zip   # path relative to repo root
          use_existing_version_if_available: true
          wait_for_deployment: true